WE-115 find 페이지 완성
42Heroes/42WLE-Front pull request #18
Opened 2022-05-31 06:47 UTC by Sara-Jo

## ✅ PR check list

- [x] PR 제목: **[Jira Ticket No]** [feat/fix/refactor] 작업 내용 한 줄 요약
- [x] commit message 에 Jira Ticket 번호가 포함되었는지 확인해주세요. 
- [x] 적절한 branch로 요청했는지 확인해주세요.
- [x] Assignees, Label을 붙여주세요.
- [x] 주의 사항과 관련해 꼭 확인해야 할 사람이 있다면 Reviewer로 등록해주세요.
- [x] PR이 승인된 경우 해당 브랜치는 삭제해 주세요!

<br/>

## 📝 Changes

find 페이지가 완성되었습니다!!

- 서버에 저장된 전체 유저를 카드형식으로 뿌려줍니다.
- 프로필 카드를 누르면 상세 프로필이 모달창으로 띄워집니다.
- 네이티브/배우는 언어별로 필터링도 가능합니다.
- 프로필카드와 필터드롭다운은 미디어쿼리가 적용되어 있습니다.

closes: #17 

<br/>

## 👨🏻‍💻 Test Checklist

- [ ] 이러한 테스트를 했어요!

## 📌 변경 및 주의 사항

<br/>

2022-05-31 06:53 UTC, jooocy reviewed
주우석 지워주세요

2022-05-31 07:01 UTC, Seojunhwan requested changes
수고하셨읍니다,,
스크린샷 정도 올려주시면 보는데 편할 것 같슴당

2022-05-31 07:01 UTC, Seojunhwan commented on pages/find.tsx
> +  const me: User = {
'Auth.tsx` 에서 리코일 유저에 임시 유저 데이터를 적용해주었기에 리코일의 유저상태를 불러오는 것이 좋을 것 같습니다!

2022-05-31 07:01 UTC, Seojunhwan commented on components/common/UserCard.tsx
> +              userCardData.nickname && user.nickname === userCardData.nickname,
요거 조건 한 번 확인해주세요!!!

2022-05-31 07:01 UTC, Seojunhwan commented on components/profile/Profile.tsx
> +          {user.hashtags && user.hashtags.length ? (
요것두 한 번 확인해주시겠어요?!

2022-05-31 07:01 UTC, Seojunhwan commented on pages/find.tsx
> +const Temp = styled.div`
컴포넌트 이름을 wrapper 등으로 설정하는 것은 어떠신가요?

2022-05-31 07:01 UTC, Seojunhwan commented on pages/find.tsx
> +  ${media.large} {
요거 미디어쿼리 하나 줄여도 될 것 같아요

2022-05-31 07:01 UTC, Seojunhwan commented on pages/find.tsx
> +          return (
중괄호 말구 소괄호로 바꿔서 리턴문을 단순화하는 것이 좋을 것 같아요

2022-06-05 06:34 UTC, Seojunhwan commented on pages/find.tsx
> +  const me: User = {
수정했습니당

2022-06-05 06:35 UTC, Seojunhwan approved these changes

2022-06-05 06:36 UTC, merged