채팅 이미지 전송 기능 추가
42Heroes/42WLE-Front pull request #38
Opened 2022-08-10 07:07 UTC by Sara-Jo

## ✅ PR check list

- [x] PR 제목: **[Jira Ticket No]** [feat/fix/refactor] 작업 내용 한 줄 요약
- [x] commit message 에 Jira Ticket 번호가 포함되었는지 확인해주세요. 
- [x] 적절한 branch로 요청했는지 확인해주세요.
- [x] Assignees, Label을 붙여주세요.
- [x] 주의 사항과 관련해 꼭 확인해야 할 사람이 있다면 Reviewer로 등록해주세요.
- [x] PR이 승인된 경우 해당 브랜치는 삭제해 주세요!

<br/>

## 📝 Changes

- 채팅 인풋 창에서 이미지 파일을 클릭하면, 선택한 이미지의 미리보기가 렌더되며 캔슬버튼이 생기고 전송버튼이 활성화됩니다.
- 캔슬 버튼을 누르면 선택한 이미지가 사라지고 다시 text input창으로 돌아갑니다.
- 이미지 선택후 전송버튼을 누르면 전송 및 채팅창에 렌더가 잘 이루어집니다.
- 마지막 메시지가 이미지인 경우에는 chatRoomList의 마지막 메시지 부분에 'Image'라고 표시됩니다.

![image](https://user-images.githubusercontent.com/77488015/183836826-03c65f41-1b37-4bdb-918b-27d5d4108dac.png)

![image](https://user-images.githubusercontent.com/77488015/183836757-828e85f7-303d-4c0a-89ec-f908d1ba00e7.png)

![image](https://user-images.githubusercontent.com/77488015/183837020-5f0efe75-21f3-4f4f-a7bf-fed076e05910.png)

<br/>

## 👨🏻‍💻 Test Checklist

- [ ] 이러한 테스트를 했어요!

## 📌 변경 및 주의 사항

<br/>

2022-08-13 11:17 UTC, Seojunhwan requested changes
이미지 전송 관련해서는 조금 더 처리가 필요해 보입니다!
현재 방식은 이미지 자체를 서버에게 주고 받으며, MongoDB 에게도 이미지 자체를 저장하고 있습니다.
조금 더 개선하여 S3 에 업로드 후 링크만 DB 에 저장하는 방법이 어떠할까 싶습니다.

2022-08-17 13:13 UTC, Sara-Jo commented
이미지를 S3 에 업로드 후에 링크를 서버로 보내는 방식으로 수정했습니다.
image input의 onChange에서는 이미지 파일을 상태로 관리하고 있다가, 전송 버튼을 눌렀을 때 이미지 파일이 S3에 업로드 된 후 서버로 보내지는 방식입니다.

2022-08-18 07:30 UTC, Seojunhwan approved these changes, later dismissed
@Sara-Jo 정상 동작한다면 오케입니다!!!

2022-08-18 08:00 UTC, Seojunhwan approved these changes

2022-08-18 08:00 UTC, merged